version: 0.0
os: linux

files:
  - source: /geostore.war
    destination: /opt/tomcat8/webapps/
    
file_exists_behavior: OVERWRITE    
          
hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: ec2-user 
